### ISSUE TITLE
SDRPlay

### ISSUE THREAD

**Issue by JonInGa** [JVital2013/armsdr.com#2]
As of today, SDRPlay hasn't yet released a version of SDRConnect for Windows on Arm. It fails when attempting to install.
However....
If you have an x86 PC available, install SDRConnect on your old school windows computer, then copy the c:\program files\SDRplay folder to your new ARM platform Windows 11 Computer and put it in the same location. Create a shortcut on your desktop to c:\program files\SDRplay\SDRconnect\SDRconnect.exe
Works fine

Also, their software package SDRUno installs and runs out of the box.

These were tested by me on a Surface Pro 11 with all the latest updates.

**Comment by JonInGa** [comment]
I should also mention the latest releases of SDR# from Airspy and SDR Console (3.4 beta version) also install and run without tweaking.

**Comment by JVital2013** [comment]
Thanks for the notes! I added SDRPlay API, SDRConnect, and SDRUno to the correct spots on armsdr.com. Your testing is appreciated!

As a note, I already listed SDR# and SDR Console under the "no support" section, because while they seem to work fine from my testing (albeit, with sample drops), they are not built for arm64. It's simply emulating the program. While this works, there's a measurable performance impact. I make sure to denote all programs like this as "Works" though to give an accurate representation of the current ecosystem. The same is true for SDRConnect and SDRUno, although I cannot attest to sample drops with SDRPlay SDRs.

On the other hand, I put SDRPlay API as officially supported. While the service itself is still x86, the actual driver and API are Windows on ARM64 binaries. I'd call that official support since the important bits are native.

Thanks again!

**Comment by UbuntuPlasma** [comment]
I have an SDRPlay nRSP-ST and I wanted to use SDRConnect on my HP Snapdragon X Plus laptop but found I was getting the x64 architecture required message when running the installer. No matter what Windows compatibility options I changed, nothing got it to install. I found on the ARMSDR website that it could work if the Program Files directory was copied from a x64 machine. As mentioned above the binary is running in compatibility mode but the drivers are native for ARM. This got me wondering if I could find a way to install SDRConnect without an x64 machine.

I used horsicq/Detect-It-Easy to work out what installer SDRPlay have used. This revealed they used InnoSetup. I used innounp to extract the install files. You can then open the instal script file (.iss) in the InnoSetup Complier.
There is a line in the install script file that explicitly requires x64 systems,
**ArchitecturesAllowed=x64**
This can be changed to the following to allow x64 compatible devices,
**ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible**
Then when I went to run the script, I got a few errors related to some missing files, mostly languages and license.txt files. None of these files seemed critical, so I removed the affected lines from the script the install worked as expected.

This is quite a convoluted process but does remove the requirement for an x64 machine.
